user_1 = User.create(name: "Bobby", zip_code: 84928)
user_1.gardens << garden = Garden.create(name: 'Backyard')
Plant.new(name: 'Alice', species: 'Rose', frequency: 24, garden: garden)
Plant.new(name: 'Tom', species: 'Carrot', frequency: 12, garden: garden)
Plant.new(name: 'Elbert', species: 'Beet', frequency: 18, garden: garden)