user_1 = User.create(name: "Bobby", zip_code: 84928)
user_1.gardens << Garden.create(name: 'Backyard')
user_1.gardens.first.plants << Plant.new(name: 'Alice', species: 'Rose', frequency: 24)
user_1.gardens.first.plants << Plant.new(name: 'Tom', species: 'Carrot', frequency: 12)
user_1.gardens.first.plants << Plant.new(name: 'Elbert', species: 'Beet', frequency: 18)